{% set name = "sqlparams" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlparams-{{ version }}.tar.gz
  sha256: 3744a2ad16f71293db6505b21fd5229b4757489a9b09f3553656a1ae97ba7ca5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - sqlparams
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sqlparams/
  summary: Convert between various DB API 2.0 parameter styles.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
