{% set name = "sqlparams" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlparams-{{ version }}.tar.gz
  sha256: 032b2f949d4afbcbfa24003f6fb407f2fc8468184e3d8ca3d59ba6b30d4935bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - sqlparams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sqlparams/
  summary: Convert between various DB API 2.0 parameter styles.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
