{% set name = "sqlparams" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlparams-{{ version }}.tar.gz
  sha256: a74d4d60f07a0bd06a6f4251db07ece512af512b363f718b72bfbd4883499a29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - sqlparams
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sqlparams/
  summary: Convert between various DB API 2.0 parameter styles.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
