{% set name = "sqlparams" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlparams-{{ version }}.tar.gz
  sha256: 1abe87a0684567265b2b86f5a482d5c37db237c0268d4c81774ffedce4300199

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - sqlparams
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sqlparams/
  summary: Convert between various DB API 2.0 parameter styles.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
